### ISSUE TITLE
小说阅读界面没内容

### ISSUE THREAD

**Issue by bxxasn** [lycstar/reader_flutter#4]
小说阅读界面，不能看小说

**Comment by bxxasn** [comment]
Compiler message:
../../../.pub-cache/hosted/pub.dartlang.org/cached_network_image-0.7.0/lib/src/cached_network_image_provider.dart:46:31: Error: The argument type 'Null Function(StringBuffer)' can't be assigned to the parameter type 'Iterable<DiagnosticsNode> Function()'.
 - 'StringBuffer' is from 'dart:core'.
 - 'Iterable' is from 'dart:core'.
 - 'DiagnosticsNode' is from 'package:flutter/src/foundation/diagnostics.dart' ('../../work_fultter/sdk/flutter/packages/flutter/lib/src/foundation/diagnostics.dart').
Try changing the type of the parameter, or casting the argument to 'Iterable<DiagnosticsNode> Function()'.
        informationCollector: (StringBuffer information) {
                              ^
Compiler failed on /Users/vam/Documents/android_work/reader_flutter/lib/main.dart

**Comment by lycstar** [comment]
切换到dev试试，flutter channel dev
